# Permalinks
permalink:           pretty

# Setup
title:               Matt Eding
tagline:             Python & Data Science Blog
url:                 http://matteding.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Matt Eding
  email:             matteding@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/MattEding

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'


# --- Footer options --- #

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  rss: true
  email: "matteding@gmail.com"
# facebook: daattali
  github: MattEding
# twitter: daattali
#  reddit: yourname
#  google-plus: +DeanAttali
  linkedin: matteding
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  youtube: user/deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname

# Select which share links to show in posts
share-links-active:
  twitter: true
  facebook: true
  google: false
  linkedin: true

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "matteding.github.io" # eg. "deanattali.com/beautiful-jekyll"
